# Generated by Django 2.0.2 on 2018-02-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.SmallIntegerField(choices=[(0, 'dimanche'), (1, 'lundi'), (2, 'mardi'), (3, 'mercredi'), (4, 'jeudi'), (5, 'vendredi'), (6, 'samedi')])),
                ('open', models.SmallIntegerField(verbose_name='ouverture')),
                ('close', models.SmallIntegerField(default=0, verbose_name='fermeture')),
            ],
        ),
    ]
