# Generated by Django 2.0.2 on 2018-02-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0002_lieu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='name',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='lieu',
            name='types',
            field=models.ManyToManyField(blank=True, to='google.Type'),
        ),
    ]
