# Generated by Django 2.0.2 on 2018-02-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0003_m2m_lieu_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'Recherche'), (2, 'Mise à jour')], editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='lieu',
            name='logs',
            field=models.ManyToManyField(editable=False, to='google.Log'),
        ),
    ]
